# Generated by Django 5.2.17 on 2026-09-07 06:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nume",
                    models.CharField(blank=True, max_length=100, verbose_name="Nume"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("mesaj", models.TextField(verbose_name="Mesaj")),
                ("data", models.DateTimeField(auto_now_add=True, verbose_name="Data")),
                ("citit", models.BooleanField(default=False, verbose_name="Citit")),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=150, verbose_name="Nume produs")),
                ("brand", models.CharField(max_length=100, verbose_name="Brand")),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("ruj", "Ruj"),
                            ("gloss", "Gloss"),
                            ("blush", "Blush"),
                            ("iluminator", "Iluminator"),
                            ("pudra", "Pudră"),
                            ("fond-de-ten", "Fond de ten"),
                            ("corector", "Corector"),
                            ("primer", "Primer"),
                            ("mascara", "Mascara"),
                            ("farduri-pleoape", "Farduri de pleoape"),
                            ("creion-ochi", "Creion de ochi"),
                            ("sprancene", "Sprâncene"),
                            ("altele", "Altele"),
                        ],
                        max_length=30,
                        verbose_name="Categorie",
                    ),
                ),
                (
                    "nuanta",
                    models.CharField(
                        blank=True,
                        help_text="Opțional — nu toate categoriile au nuanță.",
                        max_length=100,
                        verbose_name="Nuanță",
                    ),
                ),
                (
                    "sursa",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Sephora, Douglas, Notino, magazin fizic...",
                        max_length=100,
                        verbose_name="Cumpărat de la",
                    ),
                ),
                (
                    "poza",
                    models.ImageField(
                        blank=True, upload_to="produse/", verbose_name="Poză"
                    ),
                ),
                (
                    "nota_mea",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Nota mea",
                    ),
                ),
                ("parerea_mea", models.TextField(verbose_name="Părerea mea")),
                (
                    "data_postarii",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data postării"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
            ],
            options={
                "ordering": ["-data_postarii"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nume",
                    models.CharField(
                        blank=True, default="anonim", max_length=60, verbose_name="Nume"
                    ),
                ),
                (
                    "nota",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="Notă",
                    ),
                ),
                (
                    "comentariu",
                    models.TextField(max_length=600, verbose_name="Comentariu"),
                ),
                ("data", models.DateTimeField(auto_now_add=True, verbose_name="Data")),
                (
                    "aprobat",
                    models.BooleanField(
                        default=True,
                        help_text="Debifează pentru a ascunde comentariul din public fără să-l ștergi.",
                        verbose_name="Aprobat",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarii",
                        to="reviews.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
    ]
