# Generated by Django 5.2.17 on 2026-09-07 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nume",
                    models.CharField(max_length=150, verbose_name="Nume colecție"),
                ),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                (
                    "descriere",
                    models.TextField(
                        blank=True,
                        help_text="Un rând-două despre ce leagă produsele din colecție.",
                        verbose_name="Descriere",
                    ),
                ),
                (
                    "coperta",
                    models.ImageField(
                        blank=True, upload_to="colectii/", verbose_name="Copertă"
                    ),
                ),
                (
                    "data_creare",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data creării"
                    ),
                ),
                (
                    "produse",
                    models.ManyToManyField(
                        blank=True,
                        related_name="colectii",
                        to="reviews.product",
                        verbose_name="Produse",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_creare"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagine",
                    models.ImageField(
                        upload_to="produse/galerie/", verbose_name="Imagine"
                    ),
                ),
                (
                    "ordine",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordine"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagini",
                        to="reviews.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagine galerie",
                "verbose_name_plural": "Imagini galerie",
                "ordering": ["ordine", "id"],
            },
        ),
    ]
