# Generated by Django 5.2.17 on 2026-09-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_collection_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("ruj", "Ruj"),
                    ("gloss", "Gloss"),
                    ("blush", "Blush"),
                    ("iluminator", "Iluminator"),
                    ("pudra", "Pudră"),
                    ("fond-de-ten", "Fond de ten"),
                    ("corector", "Corector"),
                    ("primer", "Primer"),
                    ("mascara", "Mascara"),
                    ("farduri-pleoape", "Farduri de pleoape"),
                    ("creion-ochi", "Creion de ochi"),
                    ("sprancene", "Sprâncene"),
                    ("altele", "Altele"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Categorie",
            ),
        ),
    ]
