# Generated by Django 5.2.17 on 2026-09-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_product_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="mesaj",
            field=models.TextField(max_length=4000, verbose_name="Mesaj"),
        ),
        migrations.AlterField(
            model_name="product",
            name="data_postarii",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Data postării"
            ),
        ),
    ]
