# Generated by Django 5.2.17 on 2026-09-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_alter_contactmessage_mesaj_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sursa",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Ex: Sephora, Douglas, Notino, magazin fizic...",
                max_length=100,
                verbose_name="Cumpărat de la",
            ),
        ),
    ]
