# Generated by Django 5.2.17 on 2026-09-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_alter_product_sursa"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="activ",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Debifat = ascuns pe site (soft-delete) — rămâne în admin, cu comentariile și pozele intacte, și poate fi reactivat oricând.",
                verbose_name="Activ",
            ),
        ),
    ]
