# Generated by Django 6.1.1 on 2026-09-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_product_activ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=40, unique=True, verbose_name='Nume')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag-uri',
                'ordering': ['nume'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='imagine',
            field=models.ImageField(blank=True, help_text='O poză cu produsul la tine, dacă vrei să o arăți alături de părere.', null=True, upload_to='comentarii/', verbose_name='Poză (opțional)'),
        ),
        migrations.AddField(
            model_name='product',
            name='il_recumpar',
            field=models.BooleanField(blank=True, default=None, help_text='Da/Nu doar dacă te-ai hotărât — lasă necompletat cât timp nu știi încă, altfel un produs proaspăt postat ar arăta public „nu-l recumpăr” fără să fi spus tu asta. Da = sigiliu auriu pe card.', null=True, verbose_name='Îl recumpăr'),
        ),
        migrations.AddField(
            model_name='product',
            name='pentru_cine',
            field=models.CharField(blank=True, help_text='Ex: ten gras, buze uscate, începătoare la machiaj...', max_length=150, verbose_name='Recomandat pentru'),
        ),
        migrations.AddField(
            model_name='product',
            name='pret',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cât ai plătit pe el — opțional, dar e exact ce vine să afle cineva care se întreabă dacă merită banii.', max_digits=8, null=True, verbose_name='Preț (lei)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tine_cat',
            field=models.CharField(blank=True, help_text='Ex: 8 ore, toată ziua, se șterge repede după masă...', max_length=60, verbose_name='Cât ține'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_uri',
            field=models.ManyToManyField(blank=True, related_name='produse', to='reviews.tag', verbose_name='Tag-uri'),
        ),
    ]
