# Generated by Django 5.2.17 on 2026-09-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_comment_imagine_blank_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='aprobat',
            field=models.BooleanField(db_index=True, default=True, help_text='Debifează pentru a ascunde comentariul din public fără să-l ștergi.', verbose_name='Aprobat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag_uri',
            field=models.ManyToManyField(blank=True, help_text='Atribute libere de filtrare (tip de ten, ingrediente etc.) — opțional.', related_name='produse', to='reviews.tag', verbose_name='Tag-uri'),
        ),
    ]
