# Generated by Django 5.2.17 on 2026-09-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0010_alter_comment_aprobat_alter_product_tag_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("ruj", "Ruj"),
                    ("gloss", "Gloss"),
                    ("blush", "Blush"),
                    ("iluminator", "Iluminator"),
                    ("pudra", "Pudră"),
                    ("fond-de-ten", "Fond de ten"),
                    ("corector", "Corector"),
                    ("primer", "Primer"),
                    ("mascara", "Mascara"),
                    ("farduri-pleoape", "Farduri de pleoape"),
                    ("creion-ochi", "Creion de ochi"),
                    ("sprancene", "Sprâncene"),
                    ("ser", "Ser"),
                    ("crema-hidratanta", "Cremă hidratantă"),
                    ("toner", "Toner"),
                    ("exfoliant", "Exfoliant"),
                    ("demachiant", "Demachiant"),
                    ("masca", "Mască"),
                    ("protectie-solara", "Protecție solară"),
                    ("altele", "Altele"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Categorie",
            ),
        ),
    ]
