# Generated by Django 5.2.17 on 2026-09-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_finalizeaza_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='modificat_la',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima modificare'),
        ),
        migrations.AddField(
            model_name='collection',
            name='recomandata_saptamana',
            field=models.BooleanField(default=False, help_text='Apare distinct pe prima pagină. Dacă bifezi mai multe din greșeală, se ia cea modificată cel mai recent.', verbose_name='Colecția săptămânii'),
        ),
    ]
