# Generated by Django 5.2.17 on 2026-09-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_collection_modificat_la_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='recomandata_sezon',
            field=models.BooleanField(default=False, help_text='Apare într-un bloc separat pe prima pagină. Poți bifa mai multe deodată.', verbose_name='De sezon acum'),
        ),
    ]
