# Generated by Django 5.2.17 on 2026-09-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_collection_recomandata_sezon'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='produs_brand',
            field=models.CharField(blank=True, max_length=150, verbose_name='Produsul / brandul'),
        ),
    ]
