# Generated by Django 5.2.17 on 2026-09-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0019_contactmessage_produs_brand"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("nota__isnull", True),
                    models.Q(("nota__gte", 1), ("nota__lte", 5)),
                    _connector="OR",
                ),
                name="comment_nota_intre_1_si_5_sau_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("nota_mea__gte", 1), ("nota_mea__lte", 5)),
                name="product_nota_mea_intre_1_si_5",
            ),
        ),
    ]
