# Generated by Django 5.2.17 on 2026-09-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0020_comment_comment_nota_intre_1_si_5_sau_null_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="actualizare_data",
            field=models.DateField(
                blank=True,
                help_text="Când ai scris actualizarea de mai sus — apare alături de text.",
                null=True,
                verbose_name="Data actualizării",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="actualizare_text",
            field=models.TextField(
                blank=True,
                help_text="Pentru produse testate pe termen lung — ex: „După 3 săptămâni de folosit zilnic...”. Apare într-un bloc separat, sub Părerea mea. Opțional, completează oricând mai târziu.",
                verbose_name="Actualizare după folosire",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="remarca_rapida",
            field=models.CharField(
                blank=True,
                help_text="O propoziție scurtă, ca o însemnare de jurnal — ex: „Cel mai bun ruj mat pe care l-am încercat vreodată”. Apare stilizat, ca scris de mână, lângă poză. Opțional.",
                max_length=90,
                verbose_name="Notiță rapidă",
            ),
        ),
    ]
